# Generated by Django 4.1.13 on 2023-12-22 18:48
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def assign_user_to_boards(apps, schema_editor):

    Board = apps.get_model('kanban_boards','Board')
    User = apps.get_model('auth', 'User')
    first_user = User.objects.first()

    if first_user:
        Board.objects.all().update(user=first_user)


class Migration(migrations.Migration):
    dependencies = [
        ('kanban_boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(model_name='board', name='user', field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
        migrations.RunPython(assign_user_to_boards, reverse_code=migrations.RunPython.noop),
        # Convert the field to non-nullable after the data migration
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]

   
