# Generated by Django 5.0 on 2023-12-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_boards', '0004_alter_board_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
