# Generated by Django 5.0 on 2023-12-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_boards', '0007_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
